services:
  logger-1k:
    image: alpine
    command: >
      sh -c '
        seq 1 1000 | xargs -I {} echo "Container 1 - Log line {}" > /proc/1/fd/1;
        tail -f /dev/null
      '

  logger-5k:
    image: alpine
    command: >
      sh -c '
        seq 1 5000 | xargs -I {} echo "Container 2 - Log line {}" > /proc/1/fd/1;
        tail -f /dev/null
      '

  logger-20k:
    image: alpine
    command: >
      sh -c '
        seq 1 20000 | xargs -I {} echo "Container 3 - Log line {}" > /proc/1/fd/1;
        tail -f /dev/null
      '

  logger-10k:
    image: alpine
    command: >
      sh -c '
        seq 1 10000 | xargs -I {} echo "Container 4 - Log line {}" > /proc/1/fd/1;
        tail -f /dev/null
      '
